apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    uid: EbPG8fYoz
    url: http://jaeger:16686
    jsonData:
      nodeGraph:
        enabled: true
      spanBar:
        type: "None"
  - name: Loki
    type: loki
    uid: EbPG8fYyy
    url: http://loki:3100
    jsonData:
      nodeGraph:
        enabled: true
      spanBar:
        type: "None"
  - name: Prometheus
    type: prometheus
    uid: EbPG8fYxx
    url: http://prometheus:9090
    jsonData:
      nodeGraph:
        enabled: true

